spring:
  profiles: local
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bettinggame
    username: springboot
    password: sa


logging:
  level:
    org:
      springframework: ERROR
