# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop, feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Start postgresql in docker
        run: docker-compose -f docker/docker-compose.yml up --detach
      - name: Build with Maven
        run: |
          MAVEN_OPTS=$MAVEN_OPTS:-Dorg.slf4j.simpleLogger.defaultLogLevel=WARNING
          mvn -B package --file pom.xml
      - name: Upload betting-game-*.jar
        uses: actions/upload-artifact@v2
        with:
          name: betting-game-jar
          path: target/betting-game-*.jar
